Added support for sql-formatter
purcell/sqlformat pull request #10
Opened 2023-05-22 11:50 UTC by Trisk3lion

Support for https://github.com/sql-formatter-org/sql-formatter.

2023-05-22 13:26 UTC, purcell requested changes
Thanks, looks good, but CI is failing due to a syntax error.

2023-05-22 13:26 UTC, purcell commented on sqlformat.el
> +                 (const :tag "Use \"sql-formatter\"" sql-formatter))))
CI says there's an issue with matching parens somewhere around here. :)

2023-05-23 14:07 UTC, Trisk3lion commented on sqlformat.el
> +                 (const :tag "Use \"sql-formatter\"" sql-formatter))))
Sorry for that, fixed now!

That's what you get for trying to make changes in the github editor instead of emacs...

2023-05-24 08:43 UTC, merged

2023-05-24 08:43 UTC, purcell commented
Great, thanks!

2023-05-24 08:44 UTC, purcell commented on sqlformat.el
> +                 (const :tag "Use \"sql-formatter\"" sql-formatter))))
> That's what you get for trying to make changes in the github editor instead of emacs...

Yup, been there, done that... 😂